#all bundles
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX pav: <http://purl.org/pav/>

SELECT DISTINCT ?b ?description ?label ?license ?publisher
WHERE {
   ?b rdf:type void:Dataset .
   OPTIONAL { ?b dcterms:title ?label . }
   OPTIONAL { ?b dcterms:license ?license . }
   OPTIONAL { ?b dcterms:description ?description . }
   OPTIONAL { ?b dcterms:publisher ?publisher . }
}
