	PREFIX owl: <http://www.w3.org/2002/07/owl#>
	PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
	PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
	PREFIX mw: <http://127.0.0.1/mediawiki/index.php/Special:URIResolver/>
	SELECT distinct ?coating ?chemical ?smiles
	WHERE {
	<%s> mw:Property-3AHas_Chemical_Coating ?coating.
	?coating mw:Property-3AHas_Chemical ?chemical.
	OPTIONAL {
	?chemical mw:Property-3AHas_SMILES ?smiles.
	}
	} order by ?coating ?chemical ?smiles