PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX npo:   <http://purl.bioontology.org/ontology/npo#>
PREFIX sso:   <http://semanticscience.org/resource/>

SELECT distinct ?component ?componentName ?type ?smiles 
WHERE {
  BIND (<%s> AS ?material)
  ?material npo:has_part ?component .
  ?component a ?type .
  OPTIONAL { ?component rdfs:label ?componentName }
  OPTIONAL {
    ?component sso:CHEMINF_000200 [
       a sso:CHEMINF_000018 ;
       sso:SIO_000300 ?smiles
    ]
  }
}
