PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX npo:   <http://purl.bioontology.org/ontology/npo#>
PREFIX sso:   <http://semanticscience.org/resource/>
PREFIX obo:   <http://purl.obolibrary.org/obo/>
PREFIX cito:  <http://purl.org/net/cito/>

SELECT distinct ?mgroup ?endpoint ?type ?label ?unit ?value ?range ?source
WHERE {
  BIND (<%s> AS ?material)
  ?material obo:BFO_0000056 ?mgroup .
  ?mgroup obo:OBI_0000299 ?endpoint .
  OPTIONAL { ?endpoint a ?type }
  OPTIONAL { ?endpoint rdfs:label ?label }
  OPTIONAL { ?endpoint sso:has-unit  ?unit }
  OPTIONAL { ?endpoint sso:has-value ?value }
  OPTIONAL { ?endpoint obo:STATO_0000035 ?range }
  OPTIONAL { ?endpoint cito:usesDataFrom ?source }
}
