PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mw: <http://127.0.0.1/mediawiki/index.php/Special:URIResolver/>
SELECT DISTINCT
?method ?value ?valueUnit ?valueError
WHERE {
OPTIONAL {<%s> mw:Property-3AHas_Zeta_potential ?value.}
OPTIONAL {<%s> mw:Property-3AHas_Zeta_Error ?valueError.}
OPTIONAL {<%s> mw:Property-3AHas_Zeta_Units ?valueUnit.}
OPTIONAL {<%s> mw:Property-3AHas_Zeta_Method ?method.}
}