#assay type
PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mw: <http://127.0.0.1/mediawiki/index.php/Special:URIResolver/>


SELECT distinct ?p ?t
WHERE {
#   ?mm rdf:type ?t.
   ?mm mw:Property-3AHas_Assay_Type ?p.

}

