PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mw: <http://127.0.0.1/mediawiki/index.php/Special:URIResolver/>

SELECT distinct ?p 
WHERE {
   ?p rdf:type mw:Category-3AMeasurements.
   ?p mw:Property-3AHas_Entity ?entity.
   {
   {?p mw:Property-3AHas_Endpoint_Value ?value.}
   UNION
   {?p mw:Property-3AHas_Endpoint_Value_Min ?value.}
   UNION
   {?p mw:Property-3AHas_Endpoint_Value_Max ?value.}
   }

} order by ?p
